image: node:11

stages:
  - update_apiurl
  - build
  - deploy

variables:
  ROOT_API: "http://localhost:8000/api"
  ROOT: "http://localhost:8000"

update_apiurl:
  stage: update_apiurl
  before_script:
    - "which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # # Install ssh-agent through openssh-client if not present

    # # Add the private key to this user
    # - eval $(ssh-agent -s) && ssh-add <(echo "$SSH_PRIVATE_KEY") && mkdir -p ~/.ssh
    # # Docker specific settings
    # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Config git to avoid first usage questions. Set the identity
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote set-url origin "https://$GITLAB_USER_NAME:$GITLAB_PASSWORD@gitlab.com/sandratieben/vue-tuudu.git"
    - git checkout $CI_COMMIT_REF_NAME
    #- git pull origin master #--allow-unrelated-histories
    #- git tag my-release-1.0
    - if [ "${QUERY_STRING}" ]; then echo "${QUERY_STRING}"; else echo "no query_string"; fi
    - if [ -n "${QUERY_STRING}" ]; then cp .env.prod .env.test; fi
    - if [ -n "${QUERY_STRING}" ]; then sed 's/$/?s=${QUERY_STRING}/' .env.test; fi
    - git add .
    - if [ -n "${QUERY_STRING}" ]; then git commit -m "gitlab ci [ci skip]"; else echo "nothin to commit"; fi
    - if [ -n "${QUERY_STRING}" ]; then git push --follow-tags origin master; else echo "nthin to push"; fi
  # only:
  #   - master

build site:
  stage: build
  # cache:
  #   paths:
  #     - node_modules/
  before_script:
    - echo $(ls -a)
    - mv -f .env.prod .env
    - echo $(ls -a)
    - apt-get update
    - apt-get install zip unzip nodejs -y
    - npm install --no-progress
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

# unit test:
#   #image: node:11
#   stage: test
#   script:
#   #   - npm install --progress=false
#   #   - npm run unit

deploy:
  stage: deploy
  image: ubuntu:latest
  #when: manual
  before_script:
    # Install ssh-agent if not already installed, it is required by Docker
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

  script:
    - echo "Deploy to production server"
    - echo $(ls)
    - ssh ssh-w0138428@vegane-prinzessin.de "ls"
    - ssh ssh-w0138428@vegane-prinzessin.de "ls www/htdocs/w0138428/tuudu.emsgold.de"
    - ssh ssh-w0138428@vegane-prinzessin.de "rm -rf www/htdocs/w0138428/tuudu.emsgold.de/* "

    - scp index.html favicon.ico ssh-w0138428@vegane-prinzessin.de:/www/htdocs/w0138428/tuudu.emsgold.de
    - scp -r dist ssh-w0138428@vegane-prinzessin.de:www/htdocs/w0138428/tuudu.emsgold.de
    - ssh ssh-w0138428@vegane-prinzessin.de "ls www/htdocs/w0138428/tuudu.emsgold.de"
  only:
    - master
