image: node:latest

build site:
  stage: build
  cache:
    paths:
      - node_modules/
  before_script:
    - apt-get update
    - apt-get install zip unzip nodejs -y
    - npm install --progress=false
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

# unit test:
#   #image: node:11
#   stage: test
#   script:
#   #   - npm install --progress=false
#   #   - npm run unit

deploy:
  stage: deploy
  image: ubuntu:latest
  #when: manual
  before_script:
    # Install ssh-agent if not already installed, it is required by Docker
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"

    - mkdir -p ~/.ssh

    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

  script:
    - echo "Deploy to production server"
    # scp ssh-w0138428@vegane-prinzessin.de:/tudu.emsgold.de
    - scp -r * ssh-w0138428@vegane-prinzessin.de:/tuudu.emsgold.de
    #- ssh ssh-w0138428@vegane-prinzessin.de "cd tuudu.emsgold.de && git pull && npm install && sudo systemctl rest"
  #only: master
