language: node_js
node_js:
  - "lts/*"

os:
  - linux
  - osx

stages:
  - build
  - test
  - upload
  - name: deploy
    if: branch = master

cache:
  npm: true
  directories:
    - node_modules #NPM packages

install:
  - npm install

jobs:
  include:
    - stage: build
      name: "Build"
      script: npm run build
    - stage: test
      script: npm test
    - stage: upload
      script: echo "Uploading..."
    - stage: deploy
      name: "Deploy to stagig server"
      script: echo "Deploy..."
