language: node_js
node_js:
  - "lts/*"

os:
  - linux
  - osx

stages:
  - build
  - test
  - upload
  - name: deploy
    if: branch = master

cache:
  npm: true
  directories:
    - node_modules #NPM packages

install:
  - npm install

  jobs:
    include:
      build:
        - npm build
      test:
        - npm test
      upload:
        - echo "Uploading..."
